export const heroChartData = [
  {
    name: "Vortex Stochastic",
    creator: "Shubham",
    image: "https://github.com/ShubhamPalriwala.png",
    currency: "ETH/USDT",
    roi: "43.32%",
    aum: "190k",
    profitableTrades: "68.4%",
    data: [
      { month: "January", value: 2.5 },
      { month: "February", value: 4.8 },
      { month: "March", value: 3.7 },
      { month: "April", value: 1.9 },
      { month: "May", value: 5.2 },
      { month: "June", value: 3.3 },
      { month: "July", value: 4.6 },
      { month: "August", value: 2.8 },
      { month: "September", value: 3.9 },
      { month: "October", value: 5.5 },
      { month: "November", value: 2.1 },
      { month: "December", value: 3.0 },
    ],
  },
  {
    name: "Quantum Oscillator",
    creator: "Parth",
    image: "https://github.com/AjmeraParth132.png",
    currency: "ETH/USDT",
    roi: "33.69%",
    aum: "323k",
    profitableTrades: "78.6%",
    data: [
      { month: "January", value: 11.0 },
      { month: "February", value: 27.3 },
      { month: "March", value: 14.5 },
      { month: "April", value: -12.0 },
      { month: "May", value: 30.0 },
      { month: "June", value: 22.0 },
      { month: "July", value: 27.5 },
      { month: "August", value: -9.5 },
      { month: "September", value: -8.6 },
      { month: "October", value: 37.4 },
      { month: "November", value: -8.2 },
      { month: "December", value: 29.0 },
    ],
  },
  {
    name: "Nebula Pulse",
    creator: "Ritik",
    image: "https://media.licdn.com/dms/image/v2/C5103AQEOFvC8PJ1-wA/profile-displayphoto-shrink_400_400/profile-displayphoto-shrink_400_400/0/1560971707513?e=1730937600&v=beta&t=t6vVD7K8F_1PTw56pw-ghCrpAufVsk1obUxUL9gIOgY",
    currency: "ETH/USDT",
    roi: "47.72%",
    aum: "65k",
    profitableTrades: "71.34%",
    data: [
      { month: "January", value: 19.5 },
      { month: "February", value: 31.5 },
      { month: "March", value: 25.0 },
      { month: "April", value: -10.0 },
      { month: "May", value: 19.0 },
      { month: "June", value: 24.0 },
      { month: "July", value: 26.5 },
      { month: "August", value: -11.2 },
      { month: "September", value: 17.0 },
      { month: "October", value: 35.0 },
      { month: "November", value: -5.5 },
      { month: "December", value: 30.5 },
    ],
  },
];
