export const heroChartData = [
  {
    name: "Vortex Algorithm",
    currency: "ETH/USD",
    roi: "43.32%",
    aum: "190k",
    profitableTrades: "68.4%",
    data: [
      { month: "January", value: 146 },
      { month: "February", value: 305 },
      { month: "March", value: -237 },
      { month: "April", value: -93 },
      { month: "May", value: 109 },
      { month: "June", value: -234 },
      { month: "July", value: 267 },
      { month: "August", value: -153 },
      { month: "September", value: 67 },
      { month: "October", value: 375 },
      { month: "November", value: -71 },
      { month: "December", value: 299 },
    ],
  },
  {
    name: "RSI Algorithm",
    currency: "ETH/GBP",
    roi: "33.69%",
    aum: "323k",
    profitableTrades: "78.6%",
    data: [
      { month: "January", value: 110 },
      { month: "February", value: 273 },
      { month: "March", value: 145 },
      { month: "April", value: -220 },
      { month: "May", value: 300 },
      { month: "June", value: 220 },
      { month: "July", value: 275 },
      { month: "August", value: -195 },
      { month: "September", value: -86 },
      { month: "October", value: 374 },
      { month: "November", value: -182 },
      { month: "December", value: 290 },
    ],
  },
  {
    name: "MACD Algorithm",
    currency: "ETH/EUR",
    roi: "38.72%",
    aum: "235k",
    profitableTrades: "71.34%",
    data: [
      { month: "January", value: 195 },
      { month: "February", value: 315 },
      { month: "March", value: 250 },
      { month: "April", value: -100 },
      { month: "May", value: 190 },
      { month: "June", value: 240 },
      { month: "July", value: 265 },
      { month: "August", value: -212 },
      { month: "September", value: -70 },
      { month: "October", value: 350 },
      { month: "November", value: -155 },
      { month: "December", value: 305 },
    ],
  },
];
